version: '3'
services:
  web:
    image: nginx
    ports:
    - "8080:80"
    deploy:
      replicas: 3  
  busybox:
    image: radial/busyboxplus:curl
    command: /bin/sh -c "while true; do echo $$MESSAGE; sleep 10; done"
    environment:
    - MESSAGE=Hello!